from app.db.models.membership import (
    MembershipEntitlement,
    MembershipPlan,
    PaymentTransaction,
    PaymentWebhookEvent,
    UserMembership,
)
from app.db.models.nutrition import (
    Food,
    FoodCategory,
    FoodPortion,
    FoodSubstitution,
    MealTemplate,
    NutritionGenerationJob,
    NutritionMeal,
    NutritionMealItem,
    NutritionPlan,
    NutritionPlanDay,
    ShoppingList,
    ShoppingListItem,
)
from app.db.models.progress import (
    BodyMeasurement,
    GoalHistory,
    HealthMetricSnapshot,
    ProgressPhoto,
    StrengthLog,
    WeeklyCheckin,
    WeightLog,
)
from app.db.models.training import (
    Exercise,
    ExerciseMuscleGroup,
    MuscleGroup,
    RoutineTemplate,
    TrainingDayExercise,
    TrainingGenerationJob,
    TrainingPlan,
    TrainingPlanDay,
)
from app.db.models.usage import AuditEvent, RiskSignal, UsageEvent, UserFeatureCounter
from app.db.models.user import (
    AuthSession,
    EmailVerificationToken,
    PasswordResetToken,
    User,
    UserConsent,
    UserNutritionPreference,
    UserPhysicalProfile,
    UserSafetyProfile,
    UserSecurityEvent,
    UserTrainingPreference,
)

all_models = [
    User,
    UserPhysicalProfile,
    UserTrainingPreference,
    UserNutritionPreference,
    UserSafetyProfile,
    UserConsent,
    AuthSession,
    PasswordResetToken,
    EmailVerificationToken,
    UserSecurityEvent,
    MembershipPlan,
    MembershipEntitlement,
    UserMembership,
    PaymentTransaction,
    PaymentWebhookEvent,
    MuscleGroup,
    Exercise,
    ExerciseMuscleGroup,
    RoutineTemplate,
    TrainingPlan,
    TrainingPlanDay,
    TrainingDayExercise,
    TrainingGenerationJob,
    FoodCategory,
    Food,
    FoodPortion,
    FoodSubstitution,
    MealTemplate,
    NutritionPlan,
    NutritionPlanDay,
    NutritionMeal,
    NutritionMealItem,
    ShoppingList,
    ShoppingListItem,
    NutritionGenerationJob,
    WeightLog,
    BodyMeasurement,
    StrengthLog,
    ProgressPhoto,
    WeeklyCheckin,
    GoalHistory,
    HealthMetricSnapshot,
    UsageEvent,
    UserFeatureCounter,
    AuditEvent,
    RiskSignal,
]

__all__ = [model.__name__ for model in all_models]
